--- 
id: proxycontract
name: 01 プロキシーパターン
summary: This tutorial gives a short introduction of the web3.js library, querying the block number
level: 3
tags: 
  - Remix
  - Solidity
  - Code Patterns
steps:
  - name: 1. Why
    path: 1_Why

  - name: 2. How
    path: 2_How

  - name: 3. デリゲートコール
    path: 3_Delegatecall

  - name: 4. プロキシサンプル
    path: 4_Generic_proxy_example

  - name: 5. 確認問題
    path: 5_Test

  - name: 6. ストレージ問題
    path: 6_Storage_Problem

  - name: 7. 関連情報
    path: 7_links
